### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by cdac901** [peerigon/extract-loader#29]
Hi, I have this issue, I hope you can help me. 
This problem is very curious since it was presented 2 days ago after deleting node_module and reinstalling the packages (I do not update any version packages or node), I describe:

App.jsx 
```
import 'react-table/react-table.css'
```

webpack.config.js
```
module:{
    rules:[
      ...
      {
        test: /\.css$/,
        use: [
          'style-loader/url',
          'url-loader?limit=10000',
          'extract-loader',
          'css-loader?root=' + path.resolve(__dirname, 'assets')
        ]
      }
   ]
}
```

command 
```
npm run dev-server
```

Result
```
10% building modules 1/1 modules 0 active
Project is running at http://0.0.0.0:8081/
  webpack output is served from /
Content not from webpack is served from ./build
404s will fallback to /index.html                                                
Hash: 50cfb73d68cbc86989c2
Version: webpack 3.10.0
Time: 27055ms
Asset       Size  Chunks                    Chunk Names
0.bundle.js    1.71 MB       0  [emitted]  [big]
1.bundle.js    1.51 MB       1  [emitted]  [big]
2.bundle.js     936 kB       2  [emitted]  [big]
bundle.js    3.95 MB       3  [emitted]  [big]  main
0.bundle.js.map    1.66 MB       0  [emitted]
1.bundle.js.map    1.56 MB       1  [emitted]
2.bundle.js.map    1.02 MB       2  [emitted]
bundle.js.map    4.51 MB       3  [emitted]         main
index.html  484 bytes          [emitted]
  [1] ./node_modules/react/index.js 190 bytes {3} [built]
  [276] ./node_modules/react-router-redux/es/index.js 420 bytes {3} [built]
  [277] ./node_modules/react-router-dom/es/index.js 925 bytes {3} [built]
  [282] ./theme/index.js 5.99 kB {3} [built]
  [297] ./node_modules/url/url.js 23.3 kB {3} [built]
  [366] ./node_modules/material-ui/styles/getMuiTheme.js 13.1 kB {3} [built]
  [510] multi (webpack)-dev-server/client?http://0.0.0.0:8081 babel-polyfill ./app.jsx 52 bytes {3} [built]
  [511] (webpack)-dev-server/client?http://0.0.0.0:8081 7.63 kB {3} [built]
    [531] ./node_modules/babel-polyfill/lib/index.js 833 bytes {3} [built]
  [733] ./app.jsx 8.7 kB {3} [built]
  [821] ./node_modules/material-ui/styles/MuiThemeProvider.js 2.14 kB {3} [built]
  [847] ./node_modules/react-x-ray/dist/XRay.js 2.08 kB {3} [built]
  [1268] ./node_modules/react-table/react-table.css 847 bytes {3} [built]
  [1271] ./modules/index.js 5.98 kB {3} [built]
  [1273] ./node_modules/url-loader!./assets/images/logo/blue.png 20.3 kB {3} [built]
+ 1662 hidden modules

ERROR in ./node_modules/url-loader?limit=10000!./node_modules/extract-loader/lib/extractLoader.js!./node_modules/css-loader?root=/Users/mymachine/Documents/myproject/assets!./node_modules/react-table/react-table.css
Module build failed: /Users/mymachine/Documents/myproject/node_modules/react-table/react-table.css:1
exports = module.exports = require("../css-loader/lib/css-base.js")(false);
                                                                   ^

TypeError: require(...) is not a function
at /Users/mymachine/Documents/myproject/node_modules/react-table/react-table.css:1:68
at Script.runInContext (vm.js:74:29)
at Script.runInNewContext (vm.js:80:15)
at Object.extractLoader (/Users/mymachine/Documents/myproject/node_modules/extract-loader/lib/extractLoader.js:88:12)
@ ./node_modules/react-table/react-table.css 3:1-184
@ ./app.jsx
@ multi (webpack)-dev-server/client?http://0.0.0.0:8081 babel-polyfill ./app.jsx
  Child html-webpack-plugin for "index.html":
1 asset
  [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 795 bytes {0} [built]
  [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
  [2] (webpack)/buildin/global.js 509 bytes {0} [built]
  [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile.
```

Thanks for your help

**Comment by benurb** [comment]
Can you test if the problem is fixed when you replace `lib/extractLoader.js` with:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _vm = require("vm");

var _vm2 = _interopRequireDefault(_vm);

var _path = require("path");

var _path2 = _interopRequireDefault(_path);

var _loaderUtils = require("loader-utils");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/**
 * @name LoaderContext
 * @property {function} cacheable
 * @property {function} async
 * @property {function} addDependency
 * @property {function} loadModule
 * @property {string} resourcePath
 * @property {object} options
 */

/**
 * Random placeholder. Marks the location in the source code where the result of other modules should be inserted.
 * @type {string}
 */
var rndPlaceholder = "__EXTRACT_LOADER_PLACEHOLDER__" + rndNumber() + rndNumber();

/**
 * Executes the given module's src in a fake context in order to get the resulting string.
 *
 * @this LoaderContext
 * @throws Error
 * @param {string} content - the module's src
 */
function extractLoader(content) {
    var _this = this;

    var callback = this.async();
    var options = (0, _loaderUtils.getOptions)(this) || {};
    var publicPath = options.publicPath === undefined ? this.options.output.publicPath : options.publicPath;
    var dependencies = [];
    var script = new _vm2.default.Script(content, {
        filename: this.resourcePath,
        displayErrors: true
    });
    var sandbox = {
        require: function (_require) {
            function require(_x) {
                return _require.apply(this, arguments);
            }

            require.toString = function () {
                return _require.toString();
            };

            return require;
        }(function (resourcePath) {
            var absPath = _path2.default.resolve(_path2.default.dirname(_this.resourcePath), resourcePath).split("?")[0];

            // If the required file is a css-loader helper, we just require it with node's require.
            // If the required file should be processed by a loader we do not touch it (even if it is a .js file).
            if (/^[^!]*node_modules[/\\]css-loader[/\\].*\.js$/i.test(absPath)) {
                // Mark the file as dependency so webpack's watcher is working for the css-loader helper.
                // Other dependencies are automatically added by loadModule() below
                _this.addDependency(absPath);

                return require(absPath); // eslint-disable-line import/no-dynamic-require
            }

            dependencies.push(resourcePath);

            return rndPlaceholder;
        }),
        module: {},
        exports: {}
    };

    this.cacheable();

    sandbox.module.exports = sandbox.exports;
    script.runInNewContext(sandbox);

    Promise.all(dependencies.map(loadModule, this)).then(function (sources) {
        return sources.map(
        // runModule may throw an error, so it's important that our promise is rejected in this case
        function (src, i) {
            return runModule(src, dependencies[i], publicPath);
        });
    }).then(function (results) {
        return sandbox.module.exports.toString().replace(new RegExp(rndPlaceholder, "g"), function () {
            return results.shift();
        });
    }).then(function (content) {
        return callback(null, content);
    }).catch(callback);
}

/**
 * Loads the given module with webpack's internal module loader and returns the source code.
 *
 * @this LoaderContext
 * @param {string} request
 * @returns {Promise<string>}
 */
function loadModule(request) {
    var _this2 = this;

    return new Promise(function (resolve, reject) {
        // LoaderContext.loadModule automatically calls LoaderContext.addDependency for all requested modules
        _this2.loadModule(request, function (err, src) {
            return err ? reject(err) : resolve(src);
        });
    });
}

/**
 * Executes the given CommonJS module in a fake context to get the exported string. The given module is expected to
 * just return a string without requiring further modules.
 *
 * @throws Error
 * @param {string} src
 * @param {string} filename
 * @param {string} [publicPath]
 * @returns {string}
 */
function runModule(src, filename) {
    var publicPath = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : "";

    var script = new _vm2.default.Script(src, {
        filename,
        displayErrors: true
    });
    var sandbox = {
        module: {},
        __webpack_public_path__: publicPath // eslint-disable-line camelcase
    };

    script.runInNewContext(sandbox);

    return sandbox.module.exports.toString();
}

/**
 * @returns {string}
 */
function rndNumber() {
    return Math.random().toString().slice(2);
}

// For CommonJS interoperability
module.exports = extractLoader;
exports.default = extractLoader;
```

**Comment by cdac901** [comment]
Thanks, it works!

**Comment by mattclough1** [comment]
I'm actually seeing this problem in 3.0.0?

**Comment by js2me** [comment]
Still see same problem in 3.2.0
