### ISSUE TITLE
sass compile with css: require is not defined

### ISSUE THREAD

**Issue by willin** [peerigon/extract-loader#41]
ref: https://github.com/webpack-contrib/sass-loader/issues/584

```
ERROR in ./style.scss
    Module build failed (from ./node_modules/extract-loader/lib/extractLoader.js):
    NonErrorEmittedError: (Emitted value instead of an instance of Error) ReferenceError: require is not defined
        at runLoaders (/Users/willin/Desktop/sass-demo/node_modules/webpack/lib/NormalModule.js:300:13)
        at /Users/willin/Desktop/sass-demo/node_modules/loader-runner/lib/LoaderRunner.js:364:11
        at /Users/willin/Desktop/sass-demo/node_modules/loader-runner/lib/LoaderRunner.js:230:18
        at context.callback (/Users/willin/Desktop/sass-demo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at process._tickCallback (internal/process/next_tick.js:68:7)
     @ multi (webpack)-dev-server/client?http://localhost:8081 ./style.scss
```

source: https://github.com/wshow/sass-demo

**Comment by jhnns** [comment]
Thanks for providing the test case. That really helped a lot 👏

Fixed with `v3.0.0` 🚀
